// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ApiType {
    /**
     * Creates a new ApiType instance.
     * @param {Partial<ApiType>} [$$source = {}] - The source object to create the ApiType.
     */
    constructor($$source = {}) {
        if (!("enable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enable"] = false;
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApiType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApiType}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApiType(/** @type {Partial<ApiType>} */($$parsedSource));
    }
}

export class HostType {
    /**
     * Creates a new HostType instance.
     * @param {Partial<HostType>} [$$source = {}] - The source object to create the HostType.
     */
    constructor($$source = {}) {
        if (!("enable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enable"] = false;
        }
        if (!("tls" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tls"] = "";
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (!("offline_msg" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["offline_msg"] = false;
        }
        if (!("push_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["push_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostType}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostType(/** @type {Partial<HostType>} */($$parsedSource));
    }
}

export class NoticeType {
    /**
     * Creates a new NoticeType instance.
     * @param {Partial<NoticeType>} [$$source = {}] - The source object to create the NoticeType.
     */
    constructor($$source = {}) {
        if (!("enable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enable"] = false;
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["duration"] = "";
        }
        if (!("audio" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["audio"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoticeType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NoticeType}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NoticeType(/** @type {Partial<NoticeType>} */($$parsedSource));
    }
}

export class OtherType {
    /**
     * Creates a new OtherType instance.
     * @param {Partial<OtherType>} [$$source = {}] - The source object to create the OtherType.
     */
    constructor($$source = {}) {
        if (!("html_js" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["html_js"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OtherType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OtherType}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OtherType(/** @type {Partial<OtherType>} */($$parsedSource));
    }
}

export class RepostType {
    /**
     * Creates a new RepostType instance.
     * @param {Partial<RepostType>} [$$source = {}] - The source object to create the RepostType.
     */
    constructor($$source = {}) {
        if (!("enable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enable"] = false;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["limit"] = "";
        }
        if (!("omit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["omit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepostType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepostType}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepostType(/** @type {Partial<RepostType>} */($$parsedSource));
    }
}

export class SettingType {
    /**
     * Creates a new SettingType instance.
     * @param {Partial<SettingType>} [$$source = {}] - The source object to create the SettingType.
     */
    constructor($$source = {}) {
        if (!("api" in $$source)) {
            /**
             * @member
             * @type {ApiType}
             */
            this["api"] = (new ApiType());
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {HostType}
             */
            this["host"] = (new HostType());
        }
        if (!("repost" in $$source)) {
            /**
             * @member
             * @type {RepostType}
             */
            this["repost"] = (new RepostType());
        }
        if (!("notice" in $$source)) {
            /**
             * @member
             * @type {NoticeType}
             */
            this["notice"] = (new NoticeType());
        }
        if (!("other" in $$source)) {
            /**
             * @member
             * @type {OtherType}
             */
            this["other"] = (new OtherType());
        }
        if (!("system" in $$source)) {
            /**
             * @member
             * @type {SystemType}
             */
            this["system"] = (new SystemType());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingType}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("api" in $$parsedSource) {
            $$parsedSource["api"] = $$createField0_0($$parsedSource["api"]);
        }
        if ("host" in $$parsedSource) {
            $$parsedSource["host"] = $$createField1_0($$parsedSource["host"]);
        }
        if ("repost" in $$parsedSource) {
            $$parsedSource["repost"] = $$createField2_0($$parsedSource["repost"]);
        }
        if ("notice" in $$parsedSource) {
            $$parsedSource["notice"] = $$createField3_0($$parsedSource["notice"]);
        }
        if ("other" in $$parsedSource) {
            $$parsedSource["other"] = $$createField4_0($$parsedSource["other"]);
        }
        if ("system" in $$parsedSource) {
            $$parsedSource["system"] = $$createField5_0($$parsedSource["system"]);
        }
        return new SettingType(/** @type {Partial<SettingType>} */($$parsedSource));
    }
}

export class SystemType {
    /**
     * Creates a new SystemType instance.
     * @param {Partial<SystemType>} [$$source = {}] - The source object to create the SystemType.
     */
    constructor($$source = {}) {
        if (!("enable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemType instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemType}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemType(/** @type {Partial<SystemType>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ApiType.createFrom;
const $$createType1 = HostType.createFrom;
const $$createType2 = RepostType.createFrom;
const $$createType3 = NoticeType.createFrom;
const $$createType4 = OtherType.createFrom;
const $$createType5 = SystemType.createFrom;
