// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Msg {
    /**
     * Creates a new Msg instance.
     * @param {Partial<Msg>} [$$source = {}] - The source object to create the Msg.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Msg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Msg}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Msg(/** @type {Partial<Msg>} */($$parsedSource));
    }
}

export class Plugin {
    /**
     * Creates a new Plugin instance.
     * @param {Partial<Plugin>} [$$source = {}] - The source object to create the Plugin.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("sort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort"] = 0;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plugin instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Plugin}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Plugin(/** @type {Partial<Plugin>} */($$parsedSource));
    }
}
