// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * @param {db$0.Msg} msg
 * @returns {$CancellablePromise<void>}
 */
export function GoNotification(msg) {
    return $Call.ByID(575055069, msg);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function GoOpenDashboard(id) {
    return $Call.ByID(116086630, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function GoOpenMessage(id) {
    return $Call.ByID(3307466421, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function GoOpenPlugin() {
    return $Call.ByID(921762065);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function GoOpenPluginEdit(id) {
    return $Call.ByID(971277509, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function GoOpenSetting(id) {
    return $Call.ByID(467719490, id);
}

/**
 * @param {string} url
 * @param {string} title
 * @returns {$CancellablePromise<application$0.WebviewWindow | null>}
 */
export function OpenPage(url, title) {
    return $Call.ByID(484255579, url, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = application$0.WebviewWindow.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
