// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../models/models.js";

/**
 * @param {db$0.Msg} msg
 * @returns {$CancellablePromise<db$0.Msg>}
 */
export function GoAddMessage(msg) {
    return $Call.ByID(864691936, msg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GoClearMessage() {
    return $Call.ByID(3672102914);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function GoClose() {
    return $Call.ByID(677848078);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<boolean>}
 */
export function GoDelMessage(id) {
    return $Call.ByID(274425202, id);
}

/**
 * @returns {$CancellablePromise<db$0.Msg[]>}
 */
export function GoGetDataList() {
    return $Call.ByID(238604394).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GoGetMcount() {
    return $Call.ByID(2615112176);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<db$0.Msg>}
 */
export function GoGetMessage(id) {
    return $Call.ByID(1696485597, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<db$0.Msg[]>}
 */
export function GoGetMessageList(page, pageSize) {
    return $Call.ByID(939508825, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GoGetVersion() {
    return $Call.ByID(1785485698);
}

/**
 * @param {string} str
 * @returns {$CancellablePromise<void>}
 */
export function GoLog(str) {
    return $Call.ByID(261558744, str);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function GoOnMounted(id) {
    return $Call.ByID(986644869, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function GoOpenSetting(id) {
    return $Call.ByID(1570434454, id);
}

// Private type creation functions
const $$createType0 = db$0.Msg.createFrom;
const $$createType1 = $Create.Array($$createType0);
