// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../models/models.js";

/**
 * @param {number} id
 * @returns {$CancellablePromise<boolean>}
 */
export function GoDelPlugin(id) {
    return $Call.ByID(2581259372, id);
}

/**
 * @param {db$0.Plugin} plugin
 * @returns {$CancellablePromise<number>}
 */
export function GoEditPlugin(plugin) {
    return $Call.ByID(3252801997, plugin);
}

/**
 * @param {db$0.Plugin} plugin
 * @returns {$CancellablePromise<number>}
 */
export function GoEditPluginState(plugin) {
    return $Call.ByID(988730382, plugin);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<db$0.Plugin>}
 */
export function GoGetPlugin(id) {
    return $Call.ByID(654241413, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GoGetPluginCount() {
    return $Call.ByID(2753418324);
}

/**
 * @returns {$CancellablePromise<db$0.Plugin[]>}
 */
export function GoGetPluginList() {
    return $Call.ByID(1209148001).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} state
 * @returns {$CancellablePromise<db$0.Plugin[]>}
 */
export function GoGetPluginListWithState(state) {
    return $Call.ByID(2621704614, state).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {db$0.Plugin} plugin1
 * @param {db$0.Plugin} plugin2
 * @returns {$CancellablePromise<boolean>}
 */
export function GoSwapPlugin(plugin1, plugin2) {
    return $Call.ByID(3004487486, plugin1, plugin2);
}

// Private type creation functions
const $$createType0 = db$0.Plugin.createFrom;
const $$createType1 = $Create.Array($$createType0);
