// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as setting$0 from "../setting/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function GoCheckVersion() {
    return $Call.ByID(4092292397);
}

/**
 * @returns {$CancellablePromise<setting$0.HostType>}
 */
export function GoGetHost() {
    return $Call.ByID(4133025165).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GoGetHtmlJs() {
    return $Call.ByID(2561295245);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GoGetIps() {
    return $Call.ByID(796075291).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<setting$0.SettingType>}
 */
export function GoGetSetting() {
    return $Call.ByID(1912324489).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<setting$0.SettingType>}
 */
export function GoGetSettingDefault() {
    return $Call.ByID(2050536154).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GoGetVersion() {
    return $Call.ByID(2623097693);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function GoRestart() {
    return $Call.ByID(2185465208);
}

/**
 * @param {setting$0.SettingType} settingData
 * @returns {$CancellablePromise<boolean>}
 */
export function GoSaveSetting(settingData) {
    return $Call.ByID(3335495520, settingData);
}

// Private type creation functions
const $$createType0 = setting$0.HostType.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = setting$0.SettingType.createFrom;
